### ISSUE TITLE
java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation

### ISSUE THREAD

**Issue by msmygit** [mapstruct/mapstruct.org#33] opened 2016-05-14 22:57 UTC
I'm starting afresh with MapStruct version `1.0.0.Final` and receive the following error when I attempt to execute the codebase,

`java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation`

My Maven POM has the following added already,
```
            <plugin>
				<groupId>org.bsc.maven</groupId>
				<artifactId>maven-processor-plugin</artifactId>
	            <configuration>
	                <defaultOutputDirectory>
	                    ${project.build.directory}/generated-sources/annotations
	                </defaultOutputDirectory>
	                <processors>
	                    <processor>org.mapstruct.ap.MappingProcessor</processor>
	                </processors>
	                <options>
		                <mapstruct.suppressGeneratorTimestamp>true</mapstruct.suppressGeneratorTimestamp>
            			<!-- <mapstruct.defaultComponentModel>cdi</mapstruct.defaultComponentModel> -->
	                </options>
	            </configuration>
	            <executions>
	                <execution>
	                    <id>process</id>
	                    <phase>generate-sources</phase>
	                    <goals>
	                        <goal>process</goal>
	                    </goals>
	                </execution>
	            </executions>
	            <dependencies>
	                <dependency>
	                    <groupId>org.mapstruct</groupId>
	                    <artifactId>mapstruct-processor</artifactId>
	                    <version>${org.mapstruct.version}</version>
	                </dependency>
	            </dependencies>
	        </plugin>
```
Please note that I've modified the _defaultOutputDirectory_ to be _${project.build.directory}/generated-sources/**annotations**_ (added an extra 'annotations`). If not adding that suffix, I am generating two sets of implementation, one at the generated-sources level and another at _..generated-sources/annotations_ level and that causes duplicate implementation exists error like below during compilation of the project,

`error: duplicate class: a.g.x.h.t.mappers.DMapperImpl`

The error is occurring when invoking the Mapper class using the below even though I could very well see the Implementations of the Mapper classes at _...target../generated-sources/annotations_ directory,

```
DMapper.INSTANCE.sourceToDestination(source);
```

--------------------------------

1. On a general note, I'm trying to map fields from a bean which is located at say from a package, a.b.c.Bean to another package x.y.z.Bean with about 100s of elements within it (the destination might have couple elements removed, added and renamed fields) but, I couldn't see any straight forward way of achieving this
2. There isn't good examples out there to showcase how to achieve this and hence it was really hard to get up and running with this. May be the documentation surrounding the usage could be improvised to help out others
3. In a Mapper which uses other Mappers and say the 4th occurrence uses one of the other Mapper but, the 3rd occurrence field also uses, this plugin is not intelligent enough to scan the used Mappers but, instead it is requiring to specify the other Mapper in the current file
4. Another thing about the way to identify any issues, I've already installed the [MapStruct Eclipse plug-in](https://github.com/mapstruct/mapstruct-eclipse/) but, it not helping out with anything and so, I've to do `mvn compile` on my project to identify the errors/warnings

**Comment by agudian** [comment] 2016-05-15 12:12
That is most probably a problem with how the pom is set up - the classes should only be generated once. I bet the `mapstruct-processor` module ended up on the compile classpath, which is then picked up automatically by the java compiler. My tip would be to set up your pom like it's described in our latest docs: http://mapstruct.org/documentation/1.1/reference/html/index.html#setup
```xml
...
<properties>
    <org.mapstruct.version>1.1.0.Beta1</org.mapstruct.version>
    <m2e.apt.activation>jdt_apt</m2e.apt.activation>
</properties>
...
<dependencies>
    <dependency>
        <groupId>org.mapstruct</groupId>
        <artifactId>mapstruct-jdk8</artifactId>
        <version>${org.mapstruct.version}</version>
    </dependency>
</dependencies>
...
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.5.1</version>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
                <annotationProcessorPaths>
                    <path>
                        <groupId>org.mapstruct</groupId>
                        <artifactId>mapstruct-processor</artifactId>
                        <version>${org.mapstruct.version}</version>
                    </path>
                </annotationProcessorPaths>
            </configuration>
        </plugin>
    </plugins>
</build>
...
```
If you then also have the latest [Eclipse m2e-apt](https://marketplace.eclipse.org/content/m2e-apt) plugin installed, then the annotation processor within Eclipse will be configured correctly and you won't have any trouble either in maven or in eclipse.

Regarding your other points, I don't get what you mean with 1) and hence can't see what's missing in the docs or the examples. Could you give us some more information on what you have and what you want to accomplish?
Point 3) is by design - `used` mappers are not propaged transitively. But you can define commonly used mappers in an `@MappingConfig` annotated class and reference it in your mapper.
Finally, the MapStruct Eclipse Plugin is not supposed to set up the eclipse compiler settings based on your pom - that's what m2e-apt is for. Perhaps we should make that more clear in readme of the plugin.

I'm closing this issue now. If you want to continue discussing your points, please open up a mail thread in our mapstruct-users mailing list. For actual issues or feature requests, https://github.com/mapstruct/mapstruct/issues is the right place for them. This repository / issue tracker is for the pages and documentation on mapstruct.org only.
Thanks!

**Closed by agudian** 2016-05-15 12:12 UTC
